# Generated by Django 4.2.6 on 2023-10-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('release_year', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(default='black')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements.car')),
            ],
        ),
    ]
