# Generated by Django 4.2.6 on 2023-10-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
