# Generated by Django 4.2.6 on 2023-11-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.carmodel')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements.cargeneration'),
        ),
    ]
