# Generated by Django 4.2.6 on 2023-10-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_car_created_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_timestamp',
        ),
    ]
